# Add wavelength to old runs

In [23]:
import pandas as pd
import numpy as np

In [24]:
path = "//media/SSD_floricslimani/Fish_seq/Davide/2024-10-09 - SeqFISH_Run10 - HeLa-Puro_POLR2//result_tables/"
Detection = pd.read_feather(path + "/Detection.feather")
Detection

,detection_id,acquisition_id,visual_name,filename,voxel_size,spot_size,alpha,beta,gamma,artifact_radius,cluster_size,min_spot_per_cluster,Threshold_0,threshold,color_id,image_path,image_key,location,wavelength
0,1,0,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,265,265,0,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,1,Location-01,555
1,2,10,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,235,235,0,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,2,Location-01,555
2,3,20,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,235,235,0,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,3,Location-01,555
3,4,30,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,165,165,0,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,4,Location-01,555
4,5,40,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,165,165,0,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,5,Location-01,555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,226,189,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,305,305,0,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,226,Location-10,555
226,227,199,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,185,185,0,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,227,Location-10,555
227,228,209,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,265,265,0,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,228,Location-10,555
228,229,219,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,265,265,0,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,229,Location-10,555
229,230,229,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,None,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,265,265,0,/mnt/ssd/SSD_floricslimani/Fish_seq/Davide/202...,230,Location-10,555

In [25]:
wavelengths = [555]
color_ids = [0]

Detection['color_id'] = Detection['color_id'].astype(int)
Detection['wavelength'] = 0
for color_id, wv in zip(color_ids, wavelengths) :
    loc_idx = Detection.loc[Detection['color_id'] == color_id].index
    Detection.loc[loc_idx, ["wavelength"]] = wv

Detection.value_counts(subset=["color_id","wavelength"])

color_id  wavelength
0         555           230
Name: count, dtype: int64

In [26]:
Detection.to_feather(path + "/Detection.feather")

# Update run_path

In [70]:
import pandas as pd
import numpy as np
import os

In [84]:
path = "/media/SSD_floricslimani/Fish_seq/Davide/2024-08-07 - SeqFISH_Run6 - HeLa_R2TP1-2/result_tables/"
Detection = pd.read_feather(path + "/Detection.feather")
Acquisition = pd.read_feather(path + "/Acquisition.feather")

columns = Detection.columns
for column in Detection.select_dtypes(object).columns:
    Detection[column] = Detection[column].str.replace("","")

for column in Acquisition.select_dtypes(object).columns:
    Acquisition[column] = Acquisition[column].str.replace("/mnt/ssd/SSD_floricslimani","/media/SSD_floricslimani/")
    
Detection['voxel_size'] = pd.Series([[200,97,97]]* len(Detection), dtype=object, index= Detection.index)
Detection['spot_size'] = pd.Series([[300,140,140]]* len(Detection), dtype=object, index= Detection.index)
Detection.to_feather(path + "/Detection.feather")
Detection

,detection_id,acquisition_id,visual_name,filename,voxel_size,spot_size,alpha,beta,gamma,artifact_radius,cluster_size,min_spot_per_cluster,Threshold_0,Threshold_1,threshold,color_id,image_path,image_key,location,wavelength
0,1,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,/media/SSD_floricslimani//Fish_seq/Davide/2024...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,430,400,430,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,1,Location-01,555
1,20,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,/media/SSD_floricslimani//Fish_seq/Davide/2024...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,430,400,400,1,/media/SSD_floricslimani//Fish_seq/Davide/2024...,20,Location-01,640
2,2,10,/media/SSD_floricslimani//Fish_seq/Davide/2024...,/media/SSD_floricslimani//Fish_seq/Davide/2024...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,428,348,428,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,2,Location-01,555
3,21,10,/media/SSD_floricslimani//Fish_seq/Davide/2024...,/media/SSD_floricslimani//Fish_seq/Davide/2024...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,428,348,348,1,/media/SSD_floricslimani//Fish_seq/Davide/2024...,21,Location-01,640
4,3,20,/media/SSD_floricslimani//Fish_seq/Davide/2024...,/media/SSD_floricslimani//Fish_seq/Davide/2024...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,428,348,428,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,3,Location-01,555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,378,169,/media/SSD_floricslimani//Fish_seq/Davide/2024...,/media/SSD_floricslimani//Fish_seq/Davide/2024...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,430,400,400,1,/media/SSD_floricslimani//Fish_seq/Davide/2024...,378,Location-10,640
376,360,179,/media/SSD_floricslimani//Fish_seq/Davide/2024...,/media/SSD_floricslimani//Fish_seq/Davide/2024...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,430,400,430,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,360,Location-10,555
377,379,179,/media/SSD_floricslimani//Fish_seq/Davide/2024...,/media/SSD_floricslimani//Fish_seq/Davide/2024...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,430,400,400,1,/media/SSD_floricslimani//Fish_seq/Davide/2024...,379,Location-10,640
378,361,189,/media/SSD_floricslimani//Fish_seq/Davide/2024...,/media/SSD_floricslimani//Fish_seq/Davide/2024...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,430,400,430,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,361,Location-10,555
379,380,189,/media/SSD_floricslimani//Fish_seq/Davide/2024...,/media/SSD_floricslimani//Fish_seq/Davide/2024...,"[200, 97, 97]","[300, 140, 140]",0.5,1,2,1400,300,3,430,400,400,1,/media/SSD_floricslimani//Fish_seq/Davide/2024...,380,Location-10,640

In [80]:
Acquisition.to_feather(path + "/Acquisition.feather")
Acquisition

,acquisition_id,location,cycle,full_path,fish_shape,fish_map,dapi_full_path,dapi_shape,dapi_map,fish_reodered_shape,Cycle n.,Gene1 (Ch1 - Cy5),Gene2 (Ch2 - Cy3),Barcode 1,Brcode 2,Threshold_0,Threshold_1
0,0,Location-01,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,NaN,0,POLR2A₀,POLR2B,22,25,430,400
1,1,Location-02,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,NaN,0,POLR2A₀,POLR2B,22,25,430,400
2,2,Location-03,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,NaN,0,POLR2A₀,POLR2B,22,25,430,400
3,3,Location-04,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,NaN,0,POLR2A₀,POLR2B,22,25,430,400
4,4,Location-05,0,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,NaN,0,POLR2A₀,POLR2B,22,25,430,400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,185,Location-06,18,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,NaN,18,empty1,empty2,22,15,430,400
186,186,Location-07,18,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,NaN,18,empty1,empty2,22,15,430,400
187,187,Location-08,18,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,NaN,18,empty1,empty2,22,15,430,400
188,188,Location-09,18,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,NaN,18,empty1,empty2,22,15,430,400
189,189,Location-10,18,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,/media/SSD_floricslimani//Fish_seq/Davide/2024...,NaN,NaN,NaN,18,empty1,empty2,22,15,430,400