# Open image

In [1]:
import cellpose
import pandas as pd
import numpy as np
from Sequential_Fish.tools import open_location

/home/floric/miniconda3/envs/dev/lib/python3.9/site-packages/bigfish/segmentation/nuc_segmentation.py:16: FutureWarning: The `skimage.morphology.selem` module is deprecated and will be removed in scikit-image 1.0 (`skimage.morphology.selem` has been moved to `skimage.morphology.footprints`).
  from skimage.morphology.selem import disk

In [2]:
path = "/media/SSD_floricslimani/Fish_seq/Davide/2025-04-24 - HeLa R2TP_Run12/"
location = "Location-01"
Acquisition = pd.read_feather(path + "/result_tables/Acquisition.feather")
Acquisition

,acquisition_id,location,cycle,full_path,fish_shape,fish_map,bead_channel,dapi_channel,pipeline_version,fish_reodered_shape,Cycle n.,Ch1,Ch2 - 555nm,Ch3 - 488nm,Ch4 - 405nm,Barcode 1,Barcode 2,Threshold_0,Threshold_1
0,0,Location-01,0,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",0,POLR2A,POLR2B,beads,DAPI,22,25,900,900
1,1,Location-01,1,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",1,Washout,Washout,beads,DAPI,22,25,1200,300
2,2,Location-01,2,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",2,PRPF8,ANXA5,beads,DAPI,45,3,1200,300
3,3,Location-01,3,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",3,Washout,Washout,beads,DAPI,45,3,330,300
4,4,Location-01,4,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",4,POLR1A,POLR3A,beads,DAPI,23,27,330,300
5,5,Location-01,5,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",5,Washout,Washout,beads,DAPI,23,27,331,301
6,6,Location-01,6,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",6,PCF11,SCAF8,beads,DAPI,28,30,332,302
7,7,Location-01,7,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",7,Washout,Washout,beads,DAPI,28,30,333,303
8,8,Location-01,8,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",8,SCAF4,CHERD,beads,DAPI,29,31,334,304
9,9,Location-01,9,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",9,Washout,Washout,beads,DAPI,29,31,335,305
10,10,Location-01,10,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",10,EP400,INO80,beads,DAPI,10,13,336,306
11,11,Location-01,11,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",11,Washout,Washout,beads,DAPI,10,13,337,307
12,12,Location-01,12,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",12,GTF3C1,SRCAP,beads,DAPI,12,14,338,308
13,13,Location-01,13,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",13,Washout,Washout,beads,DAPI,12,14,339,309
14,14,Location-01,14,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",14,AGO2,AGO1,beads,DAPI,19,17,340,310
15,15,Location-01,15,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",15,Washout,Washout,beads,DAPI,19,17,341,311
16,16,Location-01,16,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",16,AGO4,AGO3,beads,DAPI,21,20,342,312
17,17,Location-01,17,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",17,Washout,Washout,beads,DAPI,21,20,343,313
18,18,Location-01,18,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",18,POLR2A_18,SNAPC4,beads,DAPI,22,15,344,314
19,19,Location-01,19,/media/SSD_floricslimani/Fish_seq/Davide/2025-...,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",19,Washout,Washout,beads,DAPI,22,15,344,315
20,20,Location-01,20,None,"[66, 2004, 2004, 4]","{'c': 4, 'cycles': 0, 'x': 3, 'y': 2, 'z': 1}",2,3,0.2,"[66, 2004, 2004, 4]",20,Washout,Washout,beads,DAPI,22,15,344,315

In [3]:
image_stack = open_location(Acquisition, location)
image_stack.shape

<tifffile.TiffFile 'img000_000_00000…0000000.ome.tif'> OME series failed to read 'img020_000_000000_0000000000.ome.tif'. Missing data are zeroed

(21, 66, 2004, 2004, 4)

In [4]:
dapi_stack = image_stack[...,3]
dapi_stack = np.mean(dapi_stack, axis=0) #Mean on cycles

# drift_correction

In [5]:
from Sequential_Fish.tools import shift_array, safe_merge_no_duplicates
from bigfish.segmentation import remove_disjoint

In [6]:
Drift = pd.read_feather(path + "/result_tables/Drift.feather")
Drift = safe_merge_no_duplicates(
    Drift,
    Acquisition,
    on="acquisition_id",
    keys=["location","cycle"]
).sort_values("cycle")
Drift

,drift_id,acquisition_id,drift_type,drift_z,drift_y,drift_x,voxel_size,removed_slices,max_projection,error,phasediff,bead_size,location,cycle
0,0,0,None,0,0,0,"[200, 97, 97]",None,None,nan,nan,"[600, 200, 200]",Location-01,0
1,1,1,None,0,4,0,"[200, 97, 97]",None,False,1.0,-6.466573e-18,"[600, 200, 200]",Location-01,1
2,2,2,None,0,4,0,"[200, 97, 97]",None,False,1.0,5.370975e-18,"[600, 200, 200]",Location-01,2
3,3,3,None,0,6,0,"[200, 97, 97]",None,False,1.0,1.339292e-18,"[600, 200, 200]",Location-01,3
4,4,4,None,0,6,2,"[200, 97, 97]",None,False,1.0,-2.150283e-17,"[600, 200, 200]",Location-01,4
5,5,5,None,0,8,1,"[200, 97, 97]",None,False,1.0,2.965237e-17,"[600, 200, 200]",Location-01,5
6,6,6,None,0,7,2,"[200, 97, 97]",None,False,1.0,-1.731858e-17,"[600, 200, 200]",Location-01,6
7,7,7,None,0,8,-1,"[200, 97, 97]",None,False,1.0,3.204623e-17,"[600, 200, 200]",Location-01,7
8,8,8,None,0,8,0,"[200, 97, 97]",None,False,1.0,5.335557e-18,"[600, 200, 200]",Location-01,8
9,9,9,None,0,9,0,"[200, 97, 97]",None,False,1.0,3.959339e-17,"[600, 200, 200]",Location-01,9
10,10,10,None,0,9,0,"[200, 97, 97]",None,False,1.0,5.018895e-17,"[600, 200, 200]",Location-01,10
11,11,11,None,0,10,0,"[200, 97, 97]",None,False,1.0,5.378631e-18,"[600, 200, 200]",Location-01,11
12,12,12,None,0,10,0,"[200, 97, 97]",None,False,1.0,2.579130e-18,"[600, 200, 200]",Location-01,12
13,13,13,None,0,10,-2,"[200, 97, 97]",None,False,1.0,4.282252e-17,"[600, 200, 200]",Location-01,13
14,14,14,None,0,9,-1,"[200, 97, 97]",None,False,1.0,2.538260e-17,"[600, 200, 200]",Location-01,14
15,15,15,None,0,10,-3,"[200, 97, 97]",None,False,1.0,2.120209e-17,"[600, 200, 200]",Location-01,15
16,16,16,None,0,10,-2,"[200, 97, 97]",None,False,1.0,5.375943e-18,"[600, 200, 200]",Location-01,16
17,17,17,None,-18,0,0,"[200, 97, 97]",None,False,1.0,1.900847e-18,"[600, 200, 200]",Location-01,17
18,18,18,None,-9,0,0,"[200, 97, 97]",None,False,1.0,-6.673631e-18,"[600, 200, 200]",Location-01,18
19,19,19,None,-1,12,-4,"[200, 97, 97]",None,False,1.0,-7.392812e-17,"[600, 200, 200]",Location-01,19
20,20,20,None,0,0,0,"[200, 97, 97]",None,False,nan,0.000000e+00,"[600, 200, 200]",Location-01,20

In [7]:
image_stack_corrected = np.zeros_like(image_stack)
image_stack_corrected.shape

(21, 66, 2004, 2004, 4)

In [8]:
for cycle, signal in enumerate(image_stack) :
    drift = Drift.loc[(Drift["location"] == location) & (Drift["cycle"] == cycle), ["drift_z","drift_y","drift_x"]].to_numpy().squeeze()
    print(drift)
    image_stack_corrected[cycle] = shift_array(signal, *drift)

[0 0 0]
[0 4 0]
[0 4 0]
[0 6 0]
[0 6 2]
[0 8 1]
[0 7 2]
[ 0  8 -1]
[0 8 0]
[0 9 0]
[0 9 0]
[ 0 10  0]
[ 0 10  0]
[ 0 10 -2]
[ 0  9 -1]
[ 0 10 -3]
[ 0 10 -2]
[-18   0   0]
[-9  0  0]
[-1 12 -4]
[0 0 0]

In [9]:
dapi_stack_corrected = image_stack_corrected[...,3]
dapi_stack_corrected = np.mean(dapi_stack_corrected, axis=0) #Mean on cycles

# Segmentation

In [13]:
nucleus_model = cellpose.models.CellposeModel(gpu= True, model_type = "nuclei")
channels = [0,0]

In [14]:
nucleus_label = nucleus_model.eval(dapi_stack, diameter= 140, channels = channels, anisotropy= 3, do_3D= True)[0].astype(np.int64)
nucleus_label_corrected = nucleus_model.eval(dapi_stack_corrected, diameter= 140, channels = channels, anisotropy= 3, do_3D= True)[0].astype(np.int64)

z_axis not specified, assuming it is dim 0
if this is actually the channel_axis, use 'model.eval(channel_axis=0, ...)'
z_axis not specified, assuming it is dim 0
if this is actually the channel_axis, use 'model.eval(channel_axis=0, ...)'

In [ ]:
nucleus_label = remove_disjoint(nucleus_label)
nucleus_label_corrected = remove_disjoint(nucleus_label_corrected)

KeyboardInterrupt:

### Optional save

In [23]:
np.savez(path + "/test_segmentation", nucleus_label=nucleus_label, nucleus_label_corrected=nucleus_label_corrected)

# Napari

In [10]:
import napari
import os
os.environ["QT_QPA_PLATFORM"] = "xcb"

## drift assessment

In [ ]:
Viewer = napari.Viewer()
Viewer.add_image(image_stack[...,3], colormap= "blue", blending= "additive", scale= (200,97,97), interpolation2d= "cubic", interpolation3d= "cubic")
Viewer.add_image(image_stack_corrected[...,3],name="corrected", colormap= "blue", blending= "additive", scale= (200,97,97), interpolation2d= "cubic", interpolation3d= "cubic")
napari.run()

NameError: name 'ref' is not defined

:

## segmentation assesssment

In [ ]:
Viewer = napari.Viewer()
Viewer.add_image(dapi_stack, colormap= "blue", blending= "additive", scale= (200,97,97), interpolation2d= "cubic", interpolation3d= "cubic")
Viewer.add_image(dapi_stack_corrected, colormap= "blue", blending= "additive", scale= (200,97,97), interpolation2d= "cubic", interpolation3d= "cubic")
Viewer.add_labels(nucleus_label, scale=(200,97,97))
Viewer.add_labels(nucleus_label_corrected, scale=(200,97,97))
napari.run()

:

: